turboext/css

- css/rozhdestvenskiy.ru/style.css
> rozhdestvenskiy.ru

- css/rozhdestvenskiy.ru/style.css
@turboext/team 
screen — https://yadi.sk/i/qYjQPxgv3VNcTs
> rozhdestvenskiy.ru: smaller footer

- server.js
> fix ajax requests proxy for devServer

- cli/build.js
- package.json
> Build files at travis

- lib/server/get-host-css.js
- package.json
- server.js
- yarn.lock
@notary 
У cheerio большие проблемы с русским языком — https://github.com/cheeriojs/cheerio/issues/866
У нас из-за этого ломаются svg-спрайты
```html
<!DOCTYPE html><html><head><meta charset="utf-8"><title>&#x420;&#x43E;&#x43C;&#x430;&#x43D; &#x420;&#x43E;&#x436;&#x434;&#x435;&#x441;&#x442;&#x432;&#x435;&#x43D;&#x441;&#x43A;&#x438;&#x439;</title><link rel="canonical" href="https://rozhdestvenskiy.ru/">
```
> get rid off cheerio

- server.js
- yarn.lock
Описание PR
****
🚀 — [master](https://master.turboext.net), [pull request](https://pull-20.turboext.net)
> Remove custom styles before applying new one

- cli/checkout.js
@notary
****
🚀 — [master](https://master.turboext.net), [pull request](https://pull-21.turboext.net)
> Clean checkout directory

- package.json
- stylelint.config.js
****
🚀 — [master](https://master.turboext.net), [pull request](https://pull-26.turboext.net)
> Update path to directory for stylelint

- README.md
****
🚀 — [master](https://master.turboext.net), [pull request](https://pull-29.turboext.net)
> readme: Про оптимизацию изображений

- hosts/pikabu.ru/images/menu.svg
<p align="center">
</p>
- [Пример #1](https://yandex.ru/turbo?text=https%3A//pikabu.ru/story/interesnyie_faktyi_5867543)
- [Пример #2](https://yandex.ru/turbo?text=https%3A//pikabu.ru/story/4_mesyatsa_posle_avarii_eva_obrosla_zhirkom_i_svezhey_sherstyu_5736541)
- [Пример #3](https://yandex.ru/turbo?text=https%3A//pikabu.ru/story/detstvo_ono_raznoe_5736679)
****
https://pikabu.ru/story/interesnyie_faktyi_5867543
🚀 [master](https://master.turboext.net/turbo?text=https%3A//pikabu.ru/story/interesnyie_faktyi_5867543)
🚀 [pull request](https://pull-33.turboext.net/turbo?text=https%3A//pikabu.ru/story/interesnyie_faktyi_5867543)
https://pikabu.ru/story/4_mesyatsa_posle_avarii_eva_obrosla_zhirkom_i_svezhey_sherstyu_5736541
🚀 …
> pikabu.ru обновление

- hosts/www.drive.ru/HOSTS.yaml
- hosts/www.drive.ru/OWNERS.yaml
- hosts/www.drive.ru/menu_trigger.svg
- hosts/www.drive.ru/style.css
- https://www.drive.ru/spy/astonmartin/5afa77fcec05c4174f00001c.html
- https://www.drive.ru/business/alfaromeo/5afa87c9ec05c4905300001d.html
Fixes #28
****
🚀 [master](https://master.turboext.net)
🚀[pull request](https://pull-38.turboext.net)
> www.drive.ru

- CHANGELOG.md
- hosts/iz.ru/style.css
- hosts/pikabu.ru/style.scss
- hosts/rozhdestvenskiy.ru/style.css
- hosts/vedomosti.ru/style.css
- hosts/www.drive.ru/style.css
- stylelint.config.js
> Ограничение на селекторы с грядущим релизом

- hosts/iz.ru/style.css
> iz.ru: Исправление линтера

- hosts/www.drive2.ru/style.css
- https://yandex.ru/turbo?text=https://www.drive.ru/business/alfaromeo/5afa87c9ec05c4905300001d.html
- https://yandex.ru/turbo?text=https://www.drive.ru/spy/astonmartin/5afa77fcec05c4174f00001c.html
> drive2: Удаление markup

- hosts/pikabu.ru/style.scss
- https://yandex.ru/turbo?text=https://pikabu.ru/story/unikalnyiy_gol_5796708
> pikabu: правки для отрыва markup

- hosts/www.drive.ru/style.css
> Drive: правки для отрыва markup

- hosts/vedomosti.ru/style.css
- https://yandex.ru/turbo?text=https://vedomosti.ru/politics/articles/2018/05/28/770918-glava-yakutii-podal-otstavku
> vedomosti: правки отрыва markup

- hosts/iz.ru/style.css
> iz.ru: правка стилей шапки

- hosts/vedomosti.ru/style.css
> Vedomosti: фикс ссылок в футере

- lib/postcss.js
- server.js
- stylelint.config.js
Запрещены селекторы по атрибуту.
> Корректно открываются адреса страниц

- hosts/iz.ru/style.css
- https://yandex.ru/turbo?text=https%3A%2F%2Fiz.ru%2F765209%2F2018-07-10%2Fsk-poprosil-arestovat-rukovoditelia-tusheniia-pozhara-v-zimnei-vishne
> iz.ru: Убираем лишний горизонтальный скролл в меню

- hosts/vedomosti.ru/style.css
- hosts/www.drive.ru/style.css
- lib/server/style-middleware.js
https://github.com/turboext/css/blob/master/CHANGELOG.md#16-07-2017
> Правки для подготовки к резиновой сетке

- hosts/pikabu.ru/style.scss
Дублирую [пулреквест](https://github.com/turboext/css/pull/61/), чтобы отребейзить и влить.
> pikabu: Подготовка к резиновой сетке

- hosts/iz.ru/style.css
- hosts/vedomosti.ru/style.css
> Финальные правки для подготовки к резиновой сетке

- hosts/www.drive2.ru/style.css
- https://yandex.ru/turbo?text=https%3A%2F%2Fwww.drive2.ru%2Fl%2F507314116373775377%2F&fallback=1
> Убрать абсолютное позиционирование в шапке

- hosts/pikabu.ru/style.scss
- https://www.yandex.ru/turbo?text=https%3A%2F%2Fpikabu.ru%2Fstory%2Frossiyskiy_proizvoditel_otkryil_v_podmoskove_krupneyshiy_v_evrope_zavod_po_proizvodstvu_kolbas_6035404&fallback=1
> Pikabu.ru Исправлены пропорции аватарок в комментариях

- hosts/www.drive.ru/style.css
@tenorok 
Увеличен padding справа в шапке.
Увеличиваем отступы и тут; переопределяем их чтобы меньше зависеть от базовых стилей и сохранить совместимость
> drive.ru исправлено центрирование логотипа

- hosts/wikipedia.org/style.scss
> Fix centering on wikipedia

- hosts/wikipedia.org/OWNERS.yaml
- hosts/wikipedia.org/style.scss
- https://yandex.ru/turbo/ru.wikipedia.org/s/wiki/Слоновые
> Addresses issues with a sticky header on Wikipedia
